### ISSUE TITLE
Error while running the code on cifar-10

### ISSUE THREAD

**Issue by legendarypython** [bencottier/cgan-denoiser#1]
VValueError: Input 0 of layer geconv1 is incompatible with the layer: expected axis -1 of input shape to have value 1 but received input with shape [256, 36, 36, 3]

I updated the line "train_images.reshape" to match the new data set shape, but still get this error train_images=train_images.reshape(50000,32,32,3)

FULL ERROR: 
Traceback (most recent call last):
  File "test_cgan.py", line 217, in <module>
    train(train_dataset, config.max_epoch)
  File "test_cgan.py", line 86, in train
    train_step(x, y)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1319, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1608, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1541, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 713, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 705, in wrapper
    ), args, kwargs)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/tmpg71djzr6.py", line 11, in tf__train_step
    generated_images = ag__.converted_call(generator, None, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (inputs,), {'training': True})
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 273, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 172, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 751, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 893, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 586, in __call__
    self.name)
  File "/home/rishabh/lib/python3.6/site-packages/tensorflow/python/keras/engine/input_spec.py", line 159, in assert_input_compatibility
    ' but received input with shape ' + str(shape))
ValueError: Input 0 of layer geconv1 is incompatible with the layer: expected axis -1 of input shape to have value 1 but received input with shape [256, 36, 36, 3]

**Comment by bencottier** [comment]
Try setting `channels = 3` in `config.py`.
